[package]
name = "SpruceOS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9.23"
getrandom = { version = "0.1.14", features = ["dummy"] }
