[package]
name = "SpruceOS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.9.8"
bootloader = "0.9.23"
getrandom = { version = "0.1.14", features = ["dummy"] }
volatile = "0.2.6"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]